export const ROOM_FILTER = "ROOM_FILTER";
export const CATEGORY_FILTER = "CATEGORY_FILTER";
export const PRICE_FILTER = "PRICE_FILTER";
export const UPDATE_USER = "UPDATE_USER";
export const SEARCH_FILTER = "SEARCH_FILTER";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const ADD_CART = "ADD_CART";
